import Head from 'next/head'
import styles from '../styles/Hero.module.css'

import Navigation from "../components/Navigation"
import HeroVideo from "../components/HeroVideo"
import Hero from "../components/Hero"
import Products from "../components/Products"
import Guide from "../components/Guide"
import Map from "../components/Map"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Genesis - Petrolia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/genesis-logo-compact.png" />
      </Head>
      <main className={styles.main}>
        <Navigation />
        <Hero />
        <HeroVideo />
        <Products />
        <Guide />
        <Map />
      </main>
    </div>
  )
}
