import Head from 'next/head'
import styles from '../styles/Home.module.css'

import HeroVideo from "../components/HeroVideo"
import Products from "../components/Products"
import Map from "../components/Map"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Genesis - Petrolia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HeroVideo />
        <Products />
        <Map />
      </main>
    </div>
  )
}
